version: '3.9'
services:
  mongo:
    image: mongo:7
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - /etc/localtime:/etc/localtime:ro

  api:
    build: .
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - /etc/localtime:/etc/localtime:ro
    command: npx nodemon src/app.js
    environment:
      - USE_FIXED_OTP=true
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/repair_demo
      - CORS_ORIGINS=*
      - TZ=Asia/Shanghai
      - CHECKIN_FRONT_MAX=3
      - CHECKIN_CIRCUIT_MAX=3
      - CHECKIN_QRCODE_MAX=3
      - CHECKIN_SITE_MAX=3
      - CHECKIN_FINISH_MAX=3
    ports:
      - "8080:8080"
    depends_on:
      - mongo

volumes:
  mongo_data:
